# Generated by Django 6.0.6 on 2026-06-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('MENTOR', 'Mentor'), ('TUTOR', 'Tutor'), ('ADMIN', 'Admin')], db_index=True, max_length=20),
        ),
    ]
