# Generated by Django 6.0.6 on 2026-06-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_alter_invitation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
