# Generated by Django 6.0.6 on 2026-06-18 11:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('actor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_role', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(db_index=True, max_length=255)),
                ('entity_label', models.CharField(blank=True, max_length=255, null=True)),
                ('changes', models.JSONField(blank=True, default=dict, null=True)),
                ('context', models.JSONField(blank=True, default=dict, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='students.student')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
